import { Request, Response } from 'express';
import QRCode from 'qrcode';
import UserModel from '../models/User.js';
import PrescriptionModel from '../models/Prescription.js';

export const getEmergencyCard = async (req: Request, res: Response): Promise<void> => {
  const user = await UserModel.findById(req.user!.uid);
  if (!user) { res.status(404).json({ success: false, error: 'User not found' }); return; }

  const activeMeds = await PrescriptionModel.find({ userId: req.user!.uid, status: 'active' });

  res.json({
    success: true,
    data: {
      bloodType: user.bloodType,
      allergies: user.allergies,
      activeMedications: activeMeds.map((m: any) => `${m.drugName} ${m.dosage}`),
      emergencyContacts: user.emergencyContacts,
      emergencyToken: user.emergencyToken,
    },
  });
};

export const updateEmergencyCard = async (req: Request, res: Response): Promise<void> => {
  const user = await UserModel.findByIdAndUpdate(
    req.user!.uid,
    { $set: { bloodType: req.body.bloodType, allergies: req.body.allergies, emergencyContacts: req.body.emergencyContacts } },
    { new: true }
  );
  res.json({ success: true, data: user });
};

export const getPublicEmergencyPage = async (req: Request, res: Response): Promise<void> => {
  const user = await UserModel.findOne({ emergencyToken: req.params.token });
  if (!user) { res.status(404).send('<h1>Emergency profile not found</h1>'); return; }

  const activeMeds = await PrescriptionModel.find({ userId: user._id, status: 'active' });

  res.setHeader('Content-Type', 'text/html');
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Emergency Medical Information — ${user.name}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; background: #fff; color: #000; padding: 16px; max-width: 480px; margin: 0 auto; }
    h1 { font-size: 20px; border-bottom: 3px solid #000; padding-bottom: 8px; margin-bottom: 16px; }
    .blood { font-size: 48px; font-weight: 900; color: #c00; text-align: center; padding: 16px; border: 3px solid #c00; margin-bottom: 16px; }
    section { margin-bottom: 16px; }
    h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-bottom: 8px; }
    ul { padding-left: 20px; }
    li { margin-bottom: 4px; font-size: 14px; }
    .allergy { color: #c00; font-weight: bold; }
    footer { margin-top: 24px; font-size: 11px; color: #666; text-align: center; }
  </style>
</head>
<body>
  <h1>🚨 Emergency Medical Information</h1>
  <p style="margin-bottom:12px; font-size:14px;"><strong>Patient:</strong> ${user.name}</p>
  <div class="blood">Blood Type: ${user.bloodType}</div>
  ${user.allergies.length > 0 ? `
  <section>
    <h2>⚠️ Allergies</h2>
    <ul>${user.allergies.map((a: any) => `<li class="allergy">${a}</li>`).join('')}</ul>
  </section>` : ''}
  ${activeMeds.length > 0 ? `
  <section>
    <h2>Current Medications</h2>
    <ul>${activeMeds.map((m: any) => `<li>${m.drugName} ${m.dosage} — ${m.frequency}</li>`).join('')}</ul>
  </section>` : ''}
  ${user.emergencyContacts.length > 0 ? `
  <section>
    <h2>Emergency Contacts</h2>
    <ul>${user.emergencyContacts.map((c: any) => `<li><strong>${c.name}</strong> (${c.relationship}): ${c.phone}</li>`).join('')}</ul>
  </section>` : ''}
  <footer>Generated by MedVault &bull; For emergency use only</footer>
</body>
</html>`);
};

export const getQRImage = async (req: Request, res: Response): Promise<void> => {
  const user = await UserModel.findById(req.user!.uid, { emergencyToken: 1 });
  if (!user) { res.status(404).json({ success: false, error: 'User not found' }); return; }

  const url = `${process.env.CLIENT_URL || 'http://localhost:3001'}/api/emergency/public/${user.emergencyToken}`;
  const buffer = await QRCode.toBuffer(url, { width: 300, margin: 2 });

  res.setHeader('Content-Type', 'image/png');
  res.send(buffer);
};
